### ISSUE TITLE
Provide demo environment

### ISSUE THREAD

**Issue by d89** [h-da/geli#199]
# User Story

### As a

User

### I want:

to have a demo installation of GELI without having to install it on my own machine

### so that:

I can experiment with the platform in order to get to know if GELI is right for me.

## Acceptance criteria:

- [x] URL is already live at demo.geli.fbi.h-da.de
- [x] Autoreset functionality after X hours (Cronjob?) to a fixed database snapshot.
- [x] Demo users for every role. Passwords and user names of these users should not be changeable, every other feature of the platform should be available
- [x] Demo system should be deployed together with the live system
- [x] Uploaded files should be deleted after reset
- [x] Maybe a time counter that presents the user with the next reset time so that she/he is not confused when a reset happens during interaction with the system?

**Comment by khase** [comment]
If we implement a customizable message in issue #108 we could use this to show something like 
"DEMO - All data will be reset at 2am CEST"

**Comment by khase** [comment]
Demo environment is up and running.
It does automatically drop its database and all its uploaded files at 2am cest daily
and updates along with the live system.

We dont have a "good" database snapshot yet that we can reset to

**Comment by d89** [comment]
Sounds good! What are the credentials I can use to log in? What I would suggest: Displaying all the possible accounts in a container next to the login box so the interested user knows right away what accounts are valid for logging in.

**Comment by khase** [comment]
By this time the Databasee is completely empty after the reset. I could take a snapshot of my local database to reset to so that we have our fixture Users:
admin@test.local
teacher@test.local
teacher2@...
teacher3@...
teacher4@...
student1@...
student2@...
student3@...

**Comment by d89** [comment]
Yep, great! Would be nice if we had a few courses and some students enrolled in some of them and the teachers being permitted to administer the courses. Basically, a realtistic scenario.

**Comment by khase** [comment]
demo Environment has a set of fixtures created by my new fixtureLoader #224 

Adds more Users:

- 1x Admin
- 4x Teacher
- 5x Tutor
- 30 Students

emails follow the following template:
`<role><nr>@test.local`
for example `teacher1@test.local` or `student22@test.local`

except for the admin user.
since we only have one the email misses the number -> `admin@test.local`

all users share the same password `test`

Defines a set of courses:

- 6 courses
- 3 to 4 lectures each
- some predefined (more or less random) units each
- random teacher
- 2 to 10 random students assigned to each

The reset will be daily at 2am cest wit a simple `dropdatabase` and `restoredatabase`

**Comment by aeimer** [comment]
@khase @d89 we can close this ticket right?

**Comment by d89** [comment]
lgtm.

**Comment by aeimer** [comment]
Will close then
