### ISSUE TITLE
Refactor Code-Katas

### ISSUE THREAD

**Issue by khase** [h-da/geli#262]
- [x] Add Example Template for creation to guide Teacher.
- [x] Improve styling

### Issues

- [x] Everytime I give focus to the editor, part of the editor is selected and the whole screen scrolls up. Pretty weird behavior. Full HD with newest chrome.
- [x] If I remove the whole "validate" function and the call to the validate function (as teacher, when I define the kata), my kata passes. It should be treated as "invalid".
- [x] When I hit "save" the kata is saved and a toast message appears which is telling me "saved". However, if I did not put a name for the Kata, it is actually not saved. I would expect an error-toast to be shown instead of "saved", when the name is missing.
- [x] I can't solve the kata in the frontend, when I'm a teacher. Would be nice if we could show a hint telling me that I can't solve this, because I'm the teacher of this course or so.

**Comment by d89** [comment]
Looks pretty good now! Some remarks that need further adjustment:

- Everytime I give focus to the editor, part of the editor is selected and the whole screen scrolls up. Pretty weird behavior. Full HD with newest chrome.
- If I remove the whole "validate" function and the call to the validate function (as teacher, when I define the kata), my kata passes. It should be treated as "invalid".
- When I hit "save" the kata is saved and a toast message appears which is telling me "saved". However, if I did not put a name for the Kata, it is actually not saved. I would expect an error-toast to be shown instead of "saved", when the name is missing.
- I can't solve the kata in the frontend, when I'm a teacher. Would be nice if we could show a hint telling me that I can't solve this, because I'm the teacher of this course or so.

**Comment by khase** [comment]
i can't recreate the following issue. 
`Everytime I give focus to the editor, part of the editor is selected and the whole screen scrolls up. Pretty weird behavior. Full HD with newest chrome.`

Not on the staging system nor on my local test system

**Comment by d89** [comment]
Looks good now, except one last tiny thing: When I remove the validate() function and the call to it and then hit the "Validate" button, it says it would validate. The error only appears when I hit "Save" telling me that there has to be a validate function. Would be great if that check could happen aswell, when I validate.

**Comment by d89** [comment]
Nope, sorry.

![image](https://user-images.githubusercontent.com/423154/33341056-02b5e42c-d47e-11e7-88e5-59e4bd3773bf.png)

**Comment by d89** [comment]
Perfect 👍 !
