### ISSUE TITLE
Add Mediamanager per Course

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#265]
# User Story

### As a: 
Teacher

### I want:
to manage my media (images, videos, other filetypes) per Course

### so that:
I have to upload a file once and can use it in that course by reference

## Acceptance criteria:
comming soon
- [x] add Tab to course "Mediamanager"

## Additional info:
Helpful modules could be:
- https://www.npmjs.com/package/angular-media-preview

**Comment by utetrapp** [comment]
Each media belongs to a course. I may access media from another course and copy it into the current course (copy, no reference). Within a course I may add media from my (course) media management into a lecture. The link will be a hash based on the filename, so that I will be able to overwrite/update an existing file. If I delete a file from my media management, the system checks for existing references, warns/informs me, asks for confirmation and automatically removes the link in the content, i.e. the student should never get an missing media error.
