### ISSUE TITLE
travis prune devdependencies

### ISSUE THREAD

**Issue by khase** [h-da/geli#71]
# User Story

### As a:  
Admin

### I want:
devdependencies not to be installed in the (prod-) docker images

### so that:
the image is as small as possible

## Acceptance criteria:
- [x] only the normal dependencies are in the docker container
  - [x] API
  - Frontend (is build by webpack)

## Additional info:
prune devdependencies before docker build and publish
`npm prune --develop`

**Comment by aeimer** [comment]
The `npm install --prefix [path]` command could help us resolve this issue. Maybe we can install the node_modules with the `--prod`-flag to a separate directory which then will be copied to the docker-container instead of the "full" dependency set, with all the dev-deps in it.

<https://stackoverflow.com/a/14867050>

**Comment by aeimer** [comment]
This is done
