### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by khase** [h-da/geli#89]
# User Story

### As a: 
User

### I want:
a way to reset my password if i can't remember

### so that:
i am able to use my account again

## Acceptance criteria:
- [x] Reset link in login page 
- [x] send mail to user with reset link
- [x] reset link referes to a page where the user can set a new password
- [x] invalidate reset link if the user login succesfully / after given time (24h ??)
- [x] allow admins to change passwords of all users

**Comment by PatrickSkowronek** [comment]
Can this be closed?

**Comment by khase** [comment]
see #400

**Comment by d89** [comment]
Here is what happens if I reset another users password as admin:

`{"name":"MongoError","message":"E11000 duplicate key error collection: geli.users index: uid_1 dup key: { : null }","stack":"MongoError: E11000 duplicate key error collection: geli.users index: uid_1 dup key: { : null }\n    at Function.MongoError.create (/usr/src/app/node_modules/mongodb-core/lib/error.js:31:11)\n    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:497:72\n    at authenticateStragglers (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:443:16)\n    at Connection.messageHandler (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:477:5)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:331:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)","ok":0,"errmsg":"E11000 duplicate key error collection: geli.users index: uid_1 dup key: { : null }","code":11000,"codeName":"DuplicateKey"}`

![capture](https://user-images.githubusercontent.com/423154/34432907-bc3df0dc-ec7b-11e7-9f76-14217b9b5ea0.PNG)

**Comment by d89** [comment]
I've just seen it working for another user - maybe an issue with corrupt data on the staging system again?

**Comment by khase** [comment]
I can't recreate your scenario, it works for me in all 3 roles.
Maybe this was already fixed.

**Comment by d89** [comment]
Works 👍
